package jonatasSantos.royalLux.core.application.models.dtos.salonservicecustomerservice;

import jonatasSantos.royalLux.core.domain.enums.SalonServicesCustomerServiceStatus;

public record SalonServiceCustomerServiceCompletedUpdateUseCaseInputDto(SalonServicesCustomerServiceStatus status) {
}
